#!/bin/sh -e

# prototype #2

export ATA_TREE="${ATA_TREE:-$HOME/code/ata/tree}"
export ATA_SRC_REPO="${ATA_SRC_REPO:-$HOME/code/ata/builds}"

# currently, ata operates with a single repo and a single tree
# the directory in ATA_SRC_REPO contains source packages
# a source package currently is a directory named $name/$ver
# the directory must contain:
# an executable file named 'build'
# a newline seperated file named 'needs', where each line is a $name/$ver
# these packages will be symlinked into the package's /lib dir
# sources, which is a newline seperated set of source links
# this file format is not stable. it will change in future

# actions
# ata add pkg [ver]
# currently, ata builds packages directly into their install location
# this will change in future

# no dependency resolution at the moment 

p () {
    printf "%s\n" "$@"
}

pd () {
    printf "%s\n" "$1" >&"${2:-1}"
}

log () { 
    pd "ata: $@" 2
}
err () {
    log "$@"
    exit 1
}

dir_first () {
    for file in "$1"/*;do
        p "${file#$1/}"
        return 0
    done
}

filename_from_url () {
    old_ifs=$IFS
    IFS='/'
    set -f
    set -- $*
    
    for a in "$@"; do
        :
    done
    
    p "$a"
    set +f
    IFS=$old_ifs
}

# this will be replaced with a checksum system in future

download_file () {
    : "${XDG_CACHE_HOME:=$HOME/.local/cache}"
    dir="$XDG_CACHE_HOME/ata/$2"
    mkdir -p "$dir"
    if [ -e "$dir/$3" ]; then
        log "$3 cached"
    else
        log "downloading $3"
        log "URL: $1"
        curl "$1" -sSLo "$dir/$3"
    fi
    p "$dir/$3"
}

main () {
    case $1 in
    build)
        shift 1
        pkg=${1:?no package name provided}
        ver=$2
        [ -d "$ATA_SRC_REPO"/"$pkg" ] || err "pkg $pkg invalid"
        [ -z "$ver" ] && ver=$(dir_first "$ATA_SRC_REPO/$pkg")
        [ -d "$ATA_SRC_REPO/$pkg/$ver" ] || err "$pkg/$ver: no such version"
        
        for f in build sources; do
            [ -f "$ATA_SRC_REPO/$pkg/$ver/$f" ] || err "$pkg/$ver: no $f file"
        done
        build_dir=/tmp/ata-build-$$
        mkdir -p "$build_dir"
        
        while read -r url dir; do
            extract_to=$build_dir
            f=$(download_file "$url" "$pkg-$ver" "$(filename_from_url $url)")
            [ -z "$dir" ] || extract_to="$build_dir/$dir"
            mkdir -p "$extract_to"
            tar xf "$f" --strip-components 1 -C "$extract_to"
        done < "$ATA_SRC_REPO/$pkg/$ver/sources"
        
        if [ -f "$ATA_SRC_REPO/$pkg/$ver/needs" ]; then
            mkdir -p "$ATA_TREE/$pkg/$ver/lib"
            while read -r dep; do
                for f in "$ATA_TREE/$dep"/usr/lib/*; do
                    # Reduce the size of RPATH, and cause 
                    ln -sf "$f" "$ATA_TREE/$pkg/$ver/lib"
                done
                # CFLAGS need to be generated.
                CFLAGS="$CFLAGS -I$ATA_TREE/$dep/usr/include"
                C_INCLUDE_PATH="$ATA_TREE/$dep/usr/include:$C_INCLUDE_PATH"
            done < "$ATA_SRC_REPO/$pkg/$ver/needs"
        fi
        
        cd "$build_dir"
        
        if [ $pkg != musl-cross-make ]; then 
            export CC=x86_64-linux-musl-cc
            export CXX=x86_64-linux-musl-c++
            
            export PATH=$ATA_TREE/musl-cross-make/0.9.10/usr/bin:$PATH
            CFLAGS="-L$ATA_TREE/$pkg/$ver/lib $CFLAGS"
            export LDFLAGS="-L$ATA_TREE/$pkg/$ver/lib -Wl,-rpath,$ATA_TREE/$pkg/$ver/lib -Wl,-dynamic-linker,$ATA_TREE/musl-cross-make/0.9.10/usr/lib/ld-musl-x86_64.so.1"
        fi
        
        time1=$(date +%s)
        env -i CC=$CC CFLAGS="$CFLAGS" LDFLAGS="$LDFLAGS" PATH="$PATH" ATA_TREE="$ATA_TREE" MAKEFLAGS=${MAKEFLAGS:--j10} LD_LIBRARY_PATH="$LD_LIBRARY_PATH" C_INCLUDE_PATH="${C_INCLUDE_PATH%:}" "$ATA_SRC_REPO/$pkg/$ver/build" null "$pkg" "$ver"
        time2=$(date +%s)
        s=$((time2 - time1))
        log "build completed in ${s}s"
    ;;
    *)
        err "$1 not implemented"
    ;;
    esac
}
main "$@"
