#!/bin/sh -e

cat << EOF > config.mk
PREFIX = $ATA_TREE/$2/$3/usr
MANPREFIX = $ATA_TREE/$2/$3/usr/share/man
RANLIB = ranlib
CC = $CC
CFLAGS = $CFLAGS $LDFLAGS
LDFLAGS = $LDFLAGS
EOF

# sbase's makefile compiles each .o directly into an executable, 
# bypassing an LD step

make
make DESTDIR="$1" install
