#!/bin/sh -e

cat << EOF > config.mk
PREFIX = $ATA_TREE/$2/$3/usr
MANPREFIX = $ATA_TREE/$2/$3/usr/share/man
RANLIB = ranlib
CC = $CC
CFLAGS = $CFLAGS -static
LDFLAGS = $LDFLAGS -static
EOF

make sbase-box
make DESTDIR="$1" sbase-box-install
rm "$1/$ATA_TREE/$2/$3/usr/bin/tar" # doesn't support hyphenless args or --strip-components
