#!/bin/sh -e

export LDFLAGS="$LDFLAGS -static"

./configure \
    --prefix="$__BASE" \
    --enable-year2038 # you never know

make
make DESTDIR="$1" install
ln -s pkgconf "$1/$__BASE/bin/pkg-config"
