#!/bin/sh -e

export CFLAGS="$CFLAGS -fPIC" # bearssl doesn't build without PIC
prefix=$ATA_TREE/$2/$3/usr

make \
    CC="$CC" \
    CFLAGS="$CFLAGS" \
    LD="$CC" \
    LDFLAGS="$LDFLAGS $CFLAGS" \
    LD_LIBRARY_PATH="$LD_LIBRARY_PATH" \
    LDDLL="$CC" \
    LDDLLFLAGS="$CFLAGS $LDFLAGS -shared -Wl,-soname,libbearssl.so"

mkdir -p "$1/$prefix/bin" "$1/$prefix/include" "$1/$prefix/lib"
cp -f build/brssl "$1/$prefix/bin"
cp -f inc/* "$1/$prefix/include"
cp -f build/libbearssl.a "$1/$prefix/lib"
cp -f build/libbearssl.so "$1/$prefix/lib"
