#!/bin/sh -e

mv test.diff patches/gcc-9.4.0/0021-fix-linux-typesh.diff

base="$ATA_TREE/$2/$3/usr"

export CFLAGS=""
export CXXFLAGS="-I/usr/include"
export CPPFLAGS="-I/usr/include"

cat > config.mak << EOF
HOST = x86_64-linux-musl
TARGET = x86_64-linux-musl
COMMON_CONFIG += --disable-nls
COMMON_CONFIG += CC="x86_64-linux-musl-gcc -static --static" CXX="x86_64-linux-musl-g++ -I/usr/include -static --static"
GCC_CONFIG += --disable-libquadmath --disable-decimal-float
GCC_CONFIG += --disable-libitm
GCC_CONFIG += --disable-fixed-point
GCC_CONFIG += --disable-lto
DL_CMD = /usr/bin/curl -C - -L -o
EOF

# DL_CMD = /usr/bin/wget -c -O

mkdir -p "$1/$__BASE/lib"
ln -sf . "$1/$__BASE/x86_64-linux-musl" 
ln -sf . "$1/$__BASE/usr"

make
make DESTDIR="$1" install
ln -sf libc.so "$1/$base/lib/ld-musl-x86_64.so.1"
ln -sf x86_64-linux-musl-gcc "$1/$base/bin/gcc"
ln -sf x86_64-linux-musl-g++ "$1/$base/bin/g++"
