#!/bin/sh -e

export CPPFLAGS=""
export CFLAGS=""
export CXXFLAGS=""
mkdir -p gcc-build
cd gcc-build

../configure \
    --prefix="$__BASE" \
    --enable-default-pie \
    --enable-default-ssp \
    --enable-shared \
    --enable-threads \
    --enable-tls \
    --enable-initfini-array \
    --enable-languages=c,c++ \
    --without-included-gettext \
    --with-zstd=no \
    --with-system-zlib \
    --disable-multilib \
    --disable-libstdcxx-pch \
    --disable-symvers \
    --disable-libmpx \
    --disable-libmudflap \
    --disable-libsanitizer \
    --disable-werror \
    --enable-bootstrap \
    --target=x86_64-pc-linux-musl

make
make DESTDIR="$1" install
