#!/bin/sh -e

./configure \
    --prefix="$__BASE" \
    --libdir="$__BASE/lib" \
    --syslibdir="$__BASE/lib"

make
make DESTDIR="$1" install

mkdir -p "$1/$__BASE/bin"
ln -sf "../lib/ld-musl-x86_64.so.1" "$1/$__BASE/bin/ldd" # create an ldd for musl packages
