#!/bin/sh -e

export BUILD_ZLIB=0
export BUILD_BZIP2=0
export BZIP2_LIB=$ATA_TREE/bzip2/1.0.8/usr/lib
export BZIP2_INCLUDE=$ATA_TREE/bzip2/1.0.8/usr/include

#export CFLAGS="$CFLAGS -DNO_POSIX_2008_LOCALE -D_GNU_SOURCE"
#export LDFLAGS="$LDFLAGS -pthread"
base="$ATA_TREE/$2/$3/usr"

bash

./Configure \
    -des \
    -Dprefix="$base" -Dvendorprefix="$base" \
    -Dsitelib="$base" \
    -Dloclibpth="$ATA_TREE/$2/$3/lib" \
    -Dlocincpth="$ATA_TREE/musl-cross-make/0.9.10/usr/include" \
    -Dincpth="$ATA_TREE/musl-cross-make/0.9.10/usr/include" \
    -Dlibs="-lc -lm -lpthread -ldl -lutil -lcrypt" \
    -Duseshrplib \
    -Dusesoname \
    -Dusethreads \
    -Dinc_version_list=none \
    -Dd_sockaddr_in6=define \
    -Dccflags="$CFLAGS" \
    -Dlddlflags="-shared $LDFLAGS" \
    -Dldflags="$LDFLAGS" \
    -Doptimize="$CFLAGS" \
    -Dcc="$CC" \
    -Dman1dir="$base/share/man/man1" \
    -Dman3dir="$base/share/man/man3" \
    -Dinstallman1dir="$base/share/man/man1" \
    -Dinstallman3dir="$base/share/man/man3" \
    -Dperl_static_inline="static __inline__" \
    -Dd_static_inline \
    -Ud_csh \
    -Ud_fpos64_t \
    -Ud_off64_t \
    -Dusenm \
    -Duse64bitint \
    -Dcf_by='strata'

make
make install
