#!/bin/sh -e

make LDFLAGS="$LDFLAGS" CFLAGS="$CFLAGS" LD_LIBRARY_PATH="$LD_LIBRARY_PATH" CC="$CC"

base="$ATA_TREE/$2/$3/usr"
mkdir -p "$1/$base/bin" "$1/$base/share/man/man1"

cp -f  pigz    "$1/$base/bin"
ln -sf pigz    "$1/$base/bin/gzip"
cp  -f pigz.1  "$1/$base/share/man/man1"
ln -sf pigz.1  "$1/$base/share/man/man1/gzip.1"
