#!/bin/sh -e

# static linking fix from kiss linux 
sed 's/\(curl_LDADD =\)/\1 -all-static/' src/Makefile.in > _
mv -f _ src/Makefile.in

./configure \
    --prefix="$ATA_TREE/$2/$3/usr" \
    --enable-ipv6 \
    --enable-unix-sockets \
    --with-pic \
    --with-bearssl \
    --without-icu \
    --without-libpsl \
    --without-libidn \
    --without-libidn2 \
    --without-brotli \
    --without-zstd \
    --without-librtmp \
    --disable-docs \
    --with-ca-bundle=/etc/ssl/certs.pem

make
make DESTDIR="$1" install
