#!/bin/sh -e

mv test.diff patches/gcc-11.2.0/0021-fix-linux-typesh.diff

cat > config.mak << EOF
GCC_VER = 11.2.0
OUTPUT = $__BASE
TARGET = x86_64-linux-musl
COMMON_CONFIG += --disable-nls
COMMON_CONFIG += CC="x86_64-linux-musl-gcc -static --static" CXX="x86_64-linux-musl-g++ -static --static"
GCC_CONFIG += --disable-libquadmath --disable-decimal-float
GCC_CONFIG += --disable-libitm
GCC_CONFIG += --disable-fixed-point
GCC_CONFIG += --disable-lto
DL_CMD = curl -C - -L -o
EOF

mkdir -p "$1/$__BASE/lib"
ln -sf . "$1/$__BASE/x86_64-linux-musl" 
ln -sf . "$1/$__BASE/usr"

make
make DESTDIR="$1" install
ln -sf libc.so "$1/$__BASE/lib/ld-musl-x86_64.so.1"
ln -sf x86_64-linux-musl-gcc "$1/$__BASE/bin/gcc"
ln -sf x86_64-linux-musl-g++ "$1/$__BASE/bin/g++"
