#!/bin/sh -e

base="$ATA_TREE/$2/$3/usr"

export CFLAGS="$CFLAGS -static -DKSH_SYSTEM_PROFILE=$base/etc/profile"

export LDFLAGS="$LDFLAGS -static"

./configure \
    --prefix="$base"

make
make DESTDIR="$1" install
ln -sf oksh "$1/$base/bin/sh" 

mkdir -p "$1/$base/etc"
cp profile "$1/$base/etc"
