#!/bin/sh

export CFLAGS="$CFLAGS -static"

export LDFLAGS="$LDFLAGS -static"

./configure

base="$ATA_TREE/$2/$3/usr"

make
make DESTDIR="$1" PREFIX="$base" BINDIR="$base/bin" MANDIR="$base/share/man" install
ln -sf oksh "$1/$base/bin/sh" 
