#!/bin/sh -e

make CC="$CC $CFLAGS $LDFLAGS" -f Makefile-libbz2_so # bzip doesn't respect $CFLAGS or $LDFLAGS
make CC="$CC $CFLAGS -static $LDFLAGS" bzip2

prefix=$ATA_TREE/$2/$3/usr

mkdir -p \
    "$1/$prefix/bin" \
    "$1/$prefix/lib" \
    "$1/$prefix/include" \
    "$1/$prefix/share/man/man1"

cp -f  bzip2 bzdiff bzgrep bzmore "$1/$prefix/bin"

ln -sf bzip2 "$1/$prefix/bin/bunzip2"
ln -sf bzip2 "$1/$prefix/bin/bzcat"

cp -f libbz2.so.1.0.8 libbz2.a "$1/$prefix/lib"

ln -sf libbz2.so.1.0.8 "$1/$prefix/lib/libbz2.so"
ln -sf libbz2.so.1.0.8 "$1/$prefix/lib/libbz2.so.1"
ln -sf libbz2.so.1.0.8 "$1/$prefix/lib/libbz2.so.1.0"

cp -f bzip2.1 "$1/$prefix/share/man/man1"
cp -f bzlib.h "$1/$prefix/include"

